---

{{ readFile "../config/repositories.yaml" }}

templates:
  default:
    version: '{{`{{ .Values.istio.chart_version }}`}}'

releases:
  - name: istio-base
    chart: istio/base
    namespace: istio-system
    set:
      - name: defaultRevision
        value: default
    createNamespace: true
    wait: true

  - name: istio-cni
    chart: istio/cni
    namespace: kube-system
    condition: istio_cni.enabled

  - name: istiod
    chart: istio/istiod
    namespace: istio-system
    createNamespace: true

  - name: istio-ingressgateway
    chart: istio/gateway
    namespace: istio-ingress
    createNamespace: true
    values:
      - {{ toYaml .Values.istio_ingress | nindent 8 }}

environments:
  default:
    values:
      - ../environments/common/cert-manager.yaml
      - ../environments/common/trust-manager.yaml
      - ../environments/common/wildcard-cert.yaml
      - ../environments/default/cert-manager.yaml
      - ../environments/default/wildcard-cert.yaml
      - ../environments/default/istio.yaml
      - ../environments/default/istio_ingress.yaml
    missingFileHandler: Error
