---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.selfIssuer.name | quote}}
  labels:
    {{- include "cert-manager-ca.labels" . | nindent 4 }}
spec:
{{- with .Values.selfIssuer }}
  selfSigned: {}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.caCert.name | quote }}
  labels:
    {{- include "cert-manager-ca.labels" . | nindent 4 }}
spec:
  commonName: {{ .Values.caCert.commonName | quote }}
  {{- if .Values.caCert.emailAddresses }}
  emailAddresses:
    {{ .Values.caCert.emailAddresses | toYaml | nindent 4 }}
  {{- end }}
  isCA: true
  secretName: {{ .Values.caCert.secretName | quote }}
  secretTemplate:
    {{ .Values.caCert.secretTemplate | toYaml | nindent 4 }}
  {{- if .Values.caCert.subject }}
  subject:
    {{ .Values.caCert.subject | toYaml | nindent 4 }}
  {{- end }}
  usages:
    {{ .Values.caCert.usages | toYaml | nindent 4 }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.selfIssuer.name | quote }}
    namespace: {{ .Values.namespace | quote }}
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.caIssuer.name | quote }}
  labels:
    {{- include "cert-manager-ca.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ .Values.caCert.secretName | quote }}
